### PR TITLE
Upgrade to PHPStan 2.x

### LINKED ISSUE #1: Compatibility with PHPStan 2.x
## Detailed description

[PHPStan has just been released](https://phpstan.org/blog/phpstan-2-0-released-level-10-elephpants) and it would be great to add compatibility to this extension.

### PR DESCRIPTION
**Pull request by jdecool**
## Description

[PHPStan 2.x has just been released](https://phpstan.org/blog/phpstan-2-0-released-level-10-elephpants).

This PR upgrade the code to allow usage of this new major version.

## Motivation and context

Closes #1

## How has this been tested?

I've created unit test to ensure the code works.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

### CODE REVIEW

**Comment by jdecool** [comment]
Hey @rolfvandekrol sorry for the ping, do you have some time to look at this PR ? 🙏🏼

**Comment by jwpage** [comment]
Thanks for the PR @jdecool, this is the last extension I'm need before I can move to PHPStan 2 👍

**Comment by bbrala** [comment]
Hi, thanks for contributing!

Changes look good and do seem to pass phpstan 1 and 2. Love to see the action that has been added. I would prefer if we'd test phpstan 1 also though. Perhaps add `phpstan: [ '^1.0', '^2.0' ]` to the different actions so we test on both majors.

**Comment by bbrala** [comment]
Merging and will add testing for minor major afterwars

**Comment by jdecool** [comment]
> Changes look good and do seem to pass phpstan 1 and 2. Love to see the action that has been added. I would prefer if we'd test phpstan 1 also though. Perhaps add phpstan: [ '^1.0', '^2.0' ] to the different actions so we test on both majors.

Oh sorry, I've forget to add a test matrix to test with `--prefer-stable` and `--prefer-lowest`

**Pull request merged**
